'use client';

import { Tournament, Match } from '@/lib/db';
import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ExportBracketProps {
  tournament: Tournament;
}

const getRoundName = (round: number, totalRounds: number): string => {
  const roundsFromEnd = totalRounds - round + 1;
  if (roundsFromEnd === 1) return 'Final';
  if (roundsFromEnd === 2) return 'Semi-Final';
  if (roundsFromEnd === 3) return 'Quarter-Final';
  if (roundsFromEnd === 4) return 'Round of 16';
  if (roundsFromEnd === 5) return 'Round of 32';
  if (roundsFromEnd === 6) return 'Round of 64';
  return `Round of ${Math.pow(2, roundsFromEnd - 1)}`;
};

export default function ExportBracket({ tournament }: ExportBracketProps) {
  const getWinner = (match: Match): string | null => {
    if (match.round === 1) {
      const isByeA = (match.playerA === null || match.playerA === '') && (match.playerB !== null && match.playerB !== '');
      const isByeB = (match.playerB === null || match.playerB === '') && (match.playerA !== null && match.playerA !== '');
      if (isByeA) return match.playerB;
      if (isByeB) return match.playerA;
    }
    if (!match.completed) return null;
    return match.scoreA[0] > match.scoreB[0] ? match.playerA : match.playerB;
  };

  const exportPDF = () => {
    const matchesByRound = tournament.bracket.reduce((acc, match) => {
      if (!acc[match.round]) acc[match.round] = [];
      acc[match.round].push(match);
      return acc;
    }, {} as Record<number, Match[]>);

    const sortedRounds = Object.keys(matchesByRound).map(Number).sort((a, b) => a - b);
    const totalRounds = sortedRounds.length;

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.setFillColor(13, 13, 13);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    let yPos = 20;
    doc.setTextColor(255, 215, 0);
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text(tournament.name || 'Tournament Bracket', pageWidth / 2, yPos, { align: 'center' });
    yPos += 8;
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text('TOURNEX', pageWidth / 2, yPos, { align: 'center' });
    yPos += 6;
    doc.setDrawColor(255, 215, 0);
    doc.setLineWidth(0.5);
    doc.line(20, yPos, pageWidth - 20, yPos);
    yPos += 8;

    sortedRounds.forEach((round) => {
      const matches = matchesByRound[round];
      const roundName = getRoundName(round, totalRounds);

      if (yPos > pageHeight - 30) {
        doc.addPage();
        doc.setFillColor(13, 13, 13);
        doc.rect(0, 0, pageWidth, pageHeight, 'F');
        yPos = 20;
      }

      doc.setTextColor(255, 215, 0);
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text(roundName, 20, yPos);
      doc.setDrawColor(255, 215, 0);
      doc.setLineWidth(0.3);
      doc.line(20, yPos + 1, pageWidth - 20, yPos + 1);
      yPos += 6;

      matches.forEach((match) => {
        const winner = getWinner(match);
        const playerA = match.playerA || 'TBD';
        const playerB = match.playerB || 'TBD';
        const scoreStr = `${match.scoreA[0]}-${match.scoreB[0]}`;

        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');

        if (match.completed && winner) {
          if (winner === playerA) {
            doc.setTextColor(255, 215, 0);
            doc.text(playerA, 20, yPos);
            const w = doc.getTextWidth(playerA);
            doc.setTextColor(255, 255, 255);
            doc.text(` [${scoreStr}] ${playerB}`, 20 + w, yPos);
          } else {
            doc.setTextColor(255, 255, 255);
            doc.text(`${playerA} [${scoreStr}] `, 20, yPos);
            const w = doc.getTextWidth(`${playerA} [${scoreStr}] `);
            doc.setTextColor(255, 215, 0);
            doc.text(playerB, 20 + w, yPos);
          }
        } else {
          doc.setTextColor(255, 255, 255);
          doc.text(`${playerA} vs ${playerB}`, 20, yPos);
        }
        yPos += 7;
      });

      yPos += 7;
    });

    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text('Generated by TOURNEX', pageWidth / 2, pageHeight - 10, { align: 'center' });

    const filename = tournament.name
      ? `tournex-${tournament.name.toLowerCase().replace(/\s+/g, '-')}.pdf`
      : 'tournex-bracket.pdf';
    doc.save(filename);
  };

  return (
    <button onClick={exportPDF}
      className="flex items-center gap-2 px-3 py-2 rounded transition-colors text-sm font-semibold"
      style={{ backgroundColor: 'var(--gold)', color: 'var(--bg-primary)', border: 'none', cursor: 'pointer' }}>
      <Download size={16} />
      Export PDF
    </button>
  );
}